import json
import os
from datetime import datetime
from typing import Dict, List

SIMPLE_HTML = """<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Recon Report - {target}</title>
<style>
body{{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:20px;}}
.container{{max-width:1200px;margin:0 auto;}}
h1,h2{{color:#58a6ff;}}
h2{{border-bottom:1px solid #30363d;padding-bottom:8px;margin:30px 0 20px;}}
h3{{color:#58a6ff;margin:15px 0 5px;}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:15px;margin:20px 0;}}
.stat-card{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:20px;text-align:center;}}
.stat-card .num{{font-size:2em;font-weight:bold;color:#58a6ff;}}
.stat-card .label{{color:#8b949e;font-size:0.85em;margin-top:5px;}}
.subdomain-item{{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:10px 15px;margin:5px 0;display:flex;justify-content:space-between;}}
.alive{{border-left:4px solid #3fb950;}}
.dead{{border-left:4px solid #f85149;}}
table{{width:100%;border-collapse:collapse;margin:10px 0;}}
th,td{{padding:10px;text-align:left;border-bottom:1px solid #30363d;}}
th{{background:#161b22;color:#58a6ff;}}
tr:hover{{background:#1c2128;}}
.badge{{display:inline-block;padding:2px 8px;border-radius:12px;font-size:0.8em;margin:2px;}}
.badge-open{{background:#3fb95033;color:#3fb950;border:1px solid #3fb950;}}
.tech-tag{{display:inline-block;background:#1f6feb33;color:#58a6ff;border:1px solid #1f6feb;padding:2px 8px;border-radius:12px;margin:2px;font-size:0.85em;}}
.vuln-box{{border:2px solid;border-radius:8px;padding:15px;margin:10px 0;}}
.vuln-high{{border-color:#f85149;background:#f8514911;}}
.vuln-medium{{border-color:#d29922;background:#d2992211;}}
.vuln-low{{border-color:#3fb950;background:#3fb95011;}}
.action{{background:#1c2128;border:1px solid #30363d;border-radius:6px;padding:10px;margin-top:10px;}}
.action code{{display:block;background:#0d1117;padding:8px;border-radius:4px;margin:5px 0;color:#3fb950;font-size:0.9em;word-break:break-all;}}
.footer{{text-align:center;color:#8b949e;margin-top:40px;padding-top:20px;border-top:1px solid #30363d;font-size:0.85em;}}
.risk-high{{color:#f85149;font-weight:bold;}}
.risk-medium{{color:#d29922;font-weight:bold;}}
.risk-low{{color:#3fb950;font-weight:bold;}}
.tools-used{{margin:10px 0;}}
.tools-used span{{display:inline-block;background:#1f6feb33;color:#58a6ff;border:1px solid #1f6feb;padding:2px 8px;border-radius:10px;font-size:0.8em;margin:2px;}}
.secret-item{{background:#f8514911;border:1px solid #f85149;border-radius:4px;padding:8px;margin:5px 0;font-family:monospace;font-size:0.9em;color:#f85149;}}
@media print{{body{{background:white;color:black;}}.vuln-box{{break-inside:avoid;}}}}
</style></head>
<body><div class="container">

<h1>Bug Bounty Recon Report</h1>
<p style="color:#8b949e">Target: <strong>{target}</strong> | {date} | Duration: {duration}</p>

<div class="tools-used">Tools: {tools_html}</div>

<div class="stats">
<div class="stat-card"><div class="num">{sub_count}</div><div class="label">Subdomains</div></div>
<div class="stat-card"><div class="num">{alive_count}</div><div class="label">Live Hosts</div></div>
<div class="stat-card"><div class="num">{port_count}</div><div class="label">Open Ports</div></div>
<div class="stat-card"><div class="num">{tech_count}</div><div class="label">Technologies</div></div>
<div class="stat-card"><div class="num">{takeover_count}</div><div class="label">Takeover Vulns</div></div>
<div class="stat-card"><div class="num">{vuln_count}</div><div class="label">Nuclei Vulns</div></div>
<div class="stat-card"><div class="num">{secret_count}</div><div class="label">Secrets Found</div></div>
</div>

{vulns_html}

{whois_html}

{dns_html}

<h2>Subdomains ({sub_count})</h2>
{sub_html}

<h2>Open Ports ({port_count})</h2>
<table><tr><th>Host</th><th>Port</th><th>Service</th><th>State</th></tr>
{port_html}
</table>

<h2>Technologies Detected ({tech_count})</h2>
{tech_html}

{ssl_html}

{secrets_html}

<div class="footer">Generated by BBRecon | {date} | Target: {target}</div>
</div></body></html>
"""

class ReportGenerator:
    def __init__(self, target: str, output_dir: str):
        self.target = target
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def _get_port_info(self, p) -> tuple:
        """Extract port and service from either dict or object"""
        if isinstance(p, dict):
            return p.get("port", 0), p.get("service", "unknown")
        else:
            return getattr(p, "port", 0), getattr(p, "service", "unknown")

    def generate_html(self, data: Dict) -> str:
        # Duration
        start = data.get("start_time", "")
        end = data.get("end_time", "")
        duration = "N/A"
        if start and end:
            try:
                s = datetime.fromisoformat(start)
                e = datetime.fromisoformat(end)
                mins = int((e - s).total_seconds() // 60)
                secs = int((e - s).total_seconds() % 60)
                duration = f"{mins}m {secs}s"
            except:
                pass

        # ===== SUBS =====
        alive_info = data.get("alive_hosts", {})
        sub_items = []
        for s in data.get("subdomains", []):
            status = ""
            techs = ""
            if s in alive_info:
                info = alive_info[s]
                if isinstance(info, dict):
                    status = info.get("status", info.get("status_code", ""))
                    if info.get("title"):
                        status += f" - {info['title']}"
                    if info.get("tech"):
                        techs = ", ".join(info["tech"][:3])
                else:
                    status = ""
            cls = "alive" if status else "dead"
            tech_display = f" | {techs}" if techs else ""
            sub_items.append(f'<div class="subdomain-item {cls}"><span>{s}</span><span>{status}{tech_display}</span></div>')
        sub_html = "\n".join(sub_items)

        # ===== PORTS =====
        port_items = []
        for h, ps in data.get("open_ports", {}).items():
            for p in ps:
                port_num, service = self._get_port_info(p)
                port_items.append(f"<tr><td>{h}</td><td>{port_num}</td><td>{service}</td><td><span class='badge badge-open'>open</span></td></tr>")
        port_html = "\n".join(port_items)

        # ===== TECH =====
        tech_items = []
        for host, techs in data.get("technologies", {}).items():
            tags = " ".join([f'<span class="tech-tag">{t}</span>' for t in techs.keys()])
            tech_items.append(f"<h3>{host}</h3><div>{tags}</div>")
        tech_html = "\n".join(tech_items) if tech_items else "<p>None detected</p>"

        # ===== SSL =====
        ssl_items = ["<h2>SSL Certificates</h2><table><tr><th>Host</th><th>Issuer</th><th>Expiry</th><th>Days Left</th></tr>"]
        for host, ssl in data.get("ssl_info", {}).items():
            ssl_items.append(f"<tr><td>{host}</td><td>{ssl.get('issuer','N/A')[:40]}</td><td>{ssl.get('not_after','N/A')}</td><td>{ssl.get('days_remaining','?')}</td></tr>")
        ssl_items.append("</table>")
        ssl_html = "\n".join(ssl_items) if data.get("ssl_info") else ""

        # ===== VULNERABILITIES =====
        vulns = []
        
        # Takeovers
        for t in data.get("takeovers", []):
            vulns.append(f"""
<div class="vuln-box vuln-high">
    <h3>Subdomain Takeover</h3>
    <p><strong class="risk-high">HIGH</strong> — {t['subdomain']}</p>
    <p>CNAME resolves to <strong>{t['service']}</strong> ({t['cname']}) — the service is not claimed.</p>
    <div class="action">
        <h4>What to do:</h4>
        <code># Verify: curl -v http://{t['subdomain']}</code>
        <code># Claim the {t['service']} service</code>
        <code># Impact: Full control of {t['subdomain']}</code>
    </div>
</div>""")

        # Expired SSL
        for host, ssl in data.get("ssl_info", {}).items():
            if ssl.get("expired"):
                vulns.append(f"""
<div class="vuln-box vuln-medium">
    <h3>Expired SSL Certificate</h3>
    <p><strong class="risk-medium">MEDIUM</strong> — {host}</p>
    <p>Certificate expired {abs(ssl.get('days_remaining',0))} days ago.</p>
    <div class="action">
        <h4>What to do:</h4>
        <code>openssl s_client -connect {host}:443 -servername {host} 2>/dev/null | openssl x509 -noout -dates</code>
        <code>Indicates poor maintenance — possible MiTM vector</code>
    </div>
</div>""")

        # Dangerous ports
        port_actions = {
            21: "FTP — try: ftp {host} (anonymous login?)",
            23: "Telnet — try: telnet {host}",
            3389: "RDP — try: xfreerdp /v:{host} /u:administrator",
            5900: "VNC — try: vncviewer {host}",
            6379: "Redis — try: redis-cli -h {host} info",
            27017: "MongoDB — try: mongo {host}",
            3306: "MySQL — try: mysql -h {host} -u root",
            1433: "MSSQL — try: sqsh -S {host} -U sa",
            445: "SMB — try: smbclient -L //{host}",
        }
        for host, ports in data.get("open_ports", {}).items():
            for p in ports:
                port_num, service = self._get_port_info(p)
                if port_num in port_actions:
                    vulns.append(f"""
<div class="vuln-box vuln-high">
    <h3>Dangerous Port: {port_num}/{service}</h3>
    <p><strong class="risk-high">HIGH</strong> — {host}:{port_num}</p>
    <div class="action">
        <h4>What to do:</h4>
        <code>{port_actions[port_num].format(host=host)}</code>
    </div>
</div>""")

        # Sensitive directories
        for url, info in data.get("directories", {}).items():
            path_part = url.rstrip("/").split("/")[-1] if url.rstrip("/").split("/")[-1] else url.rstrip("/").split("/")[-2]
            if any(kw in path_part.lower() for kw in ["admin","login","wp-admin","dashboard","config",".git",".env","backup","api"]):
                risk = "high" if path_part.lower() in [".git", ".env", "config", "backup"] else "medium"
                vulns.append(f"""
<div class="vuln-box vuln-{risk}">
    <h3>Exposed: /{path_part}</h3>
    <p><strong class="risk-{risk}">{risk.upper()}</strong> — {url}</p>
    <div class="action">
        <h4>What to do:</h4>
        <code>curl -v {url}</code>
        {f'<code>git clone {url}</code>' if '.git' in path_part else ''}
        {f'<code>curl {url} 2>/dev/null | grep -i "password\\|secret\\|api\\|key"</code>' if '.env' in path_part else ''}
        <code>Try default credentials if login panel</code>
    </div>
</div>""")

        # Nuclei vulns
        for v in data.get("nuclei_vulns", []):
            sev = v.get("severity", "medium").lower()
            vulns.append(f"""
<div class="vuln-box vuln-{sev}">
    <h3>{v.get('name', 'Unknown Vulnerability')}</h3>
    <p><strong class="risk-{sev}">{sev.upper()}</strong> — {v.get('host', 'N/A')}</p>
    <p>Template: {v.get('template', 'N/A')}</p>
    <p>{v.get('description', '')}</p>
    <div class="action">
        <h4>What to do:</h4>
        <code># Matched at: {v.get('matched', 'N/A')}</code>
        <code># Search Exploit-DB or NVD for this vulnerability</code>
    </div>
</div>""")

        vulns_html = "\n".join(vulns) if vulns else "<p>No vulnerabilities found.</p>"

        # ===== WHOIS =====
        whois = data.get("whois_dns", {}).get("whois", {})
        whois_html = ""
        if whois and "error" not in whois:
            whois_html = f"""<h2>WHOIS</h2>
<table>
<tr><td>Registrar</td><td>{whois.get('registrar','N/A')}</td></tr>
<tr><td>Organization</td><td>{whois.get('organization','N/A')}</td></tr>
<tr><td>Country</td><td>{whois.get('country','N/A')}</td></tr>
<tr><td>Created</td><td>{whois.get('creation_date','N/A')}</td></tr>
<tr><td>Expires</td><td>{whois.get('expiration_date','N/A')}</td></tr>
</table>"""

        # ===== DNS =====
        dns_records = data.get("whois_dns", {}).get("dns_records", {})
        dns_html = ""
        if dns_records:
            dns_html = "<h2>DNS Records</h2><table><tr><th>Type</th><th>Value</th></tr>"
            for rtype, values in dns_records.items():
                if values:
                    vals = ", ".join([str(v) for v in values[:5]])
                    dns_html += f"<tr><td>{rtype}</td><td>{vals}</td></tr>"
            dns_html += "</table>"

        # ===== SECRETS =====
        secrets_html = ""
        secret_count = 0
        for js in data.get("js_analysis", []):
            if js.get("secrets"):
                secret_count += len(js["secrets"])
                secrets_html += f"<h2>Secrets Found in JavaScript</h2>"
                for s in js["secrets"]:
                    secrets_html += f'<div class="secret-item">[{s["type"]}] {s["value"]}</div>'

        # ===== TOOLS =====
        tools = data.get("tools_used", [])
        tools_html = " ".join([f'<span>{t}</span>' for t in tools])

        # ===== STATS =====
        sub_count = len(data.get("subdomains", []))
        alive_count = len(alive_info)
        port_count = sum(len(v) for v in data.get("open_ports", {}).values())
        tech_count = sum(len(v) for v in data.get("technologies", {}).values())
        takeover_count = len(data.get("takeovers", []))
        vuln_count = len(data.get("nuclei_vulns", []))

        # Render
        html = SIMPLE_HTML.format(
            target=self.target,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            duration=duration,
            tools_html=tools_html,
            sub_count=sub_count,
            alive_count=alive_count,
            port_count=port_count,
            tech_count=tech_count,
            takeover_count=takeover_count,
            vuln_count=vuln_count,
            secret_count=secret_count,
            sub_html=sub_html,
            port_html=port_html,
            tech_html=tech_html,
            ssl_html=ssl_html,
            vulns_html=vulns_html,
            whois_html=whois_html,
            dns_html=dns_html,
            secrets_html=secrets_html,
        )

        path = os.path.join(self.output_dir, "report.html")
        with open(path, "w") as f:
            f.write(html)

        json_path = os.path.join(self.output_dir, "report.json")
        with open(json_path, "w") as f:
            json.dump(data, f, indent=2, default=str)

        print(f"[+] Report generated: {path}")
        return path
